ZiJingHu/Controllers/BusinessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ZiJingHu.Controllers
{
    public class BusinessController : Controller
    {
        //
        // GET: /Business/
        public ActionResult Index()
        {
            return View();
        }
	}
}

ZiJingHu/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ZiJingHu.Models;
using PagedList;

namespace ZiJingHu.Controllers
{
    public class ClientController : Controller
    {
        private ZiJingHuContext db = new ZiJingHuContext();

        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            //search
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var clients = from c in db.Clients
                          select c;

            if (!String.IsNullOrEmpty(searchString))
            {
                clients = clients.Where(o => o.Name.Contains(searchString));
            }

            //sort
            ViewBag.CurrentSort = sortOrder;
            ViewBag.ClientNameSortParm = (String.IsNullOrEmpty(sortOrder) || sortOrder == "client_name_desc") ? "client_name_desc" : "client_name";
            ViewBag.ProductNameSortParm = sortOrder == "pruduct_name" ? "pruduct_name_desc" : "pruduct_name";

            switch (sortOrder)
            {
                case "pruduct_name":
                    clients = clients.OrderBy(c => c.ProductId);
                    break;
                case "pruduct_name_desc":
                    clients = clients.OrderByDescending(c => c.ProductId);
                    break;
                case "client_name":
                    clients = clients.OrderBy(c => c.Name);
                    break;
                case "client_name_desc":
                    clients = clients.OrderByDescending(c => c.Name);
                    break;
                default:
                    clients = clients.OrderBy(c => c.Sequence);
                    break;
            }

            //page list
            int pageSize = int.Parse(System.Configuration.ConfigurationManager.AppSettings["PageSize"]);
            int pageNumber = (page ?? 1);
            return View(clients.ToPagedList(pageNumber, pageSize));
        }

        // GET: /Client/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // GET: /Client/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.ProductId = new SelectList(db.Products, "Id", "Name");
            return View();
        }

        // POST: /Client/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "Id,Name,HeadQuarter,Description,Feedback,ImageName,ProductId,Sequence")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Clients.Add(client);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProductId = new SelectList(db.Products, "Id", "Name", client.ProductId);
            return View(client);
        }

        // GET: /Client/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProductId = new SelectList(db.Products, "Id", "Name", client.ProductId);
            return View(client);
        }

        // POST: /Client/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "Id,Name,HeadQuarter,Description,Feedback,ImageName,ProductId,Sequence")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProductId = new SelectList(db.Products, "Id", "Name", client.ProductId);
            return View(client);
        }

        // GET: /Client/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: /Client/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            Client client = db.Clients.Find(id);
            db.Clients.Remove(client);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ZiJingHu/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ZiJingHu.Models;
using PagedList;

namespace ZiJingHu.Controllers
{
    public class ProductController : Controller
    {
        private ZiJingHuContext db = new ZiJingHuContext();

        // GET: /Product/
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            //search
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var products = from p in db.Products
                           select p;

            if (!String.IsNullOrEmpty(searchString))
            {
                products = products.Where(o => o.Name.Contains(searchString));
            }

            //sort
            ViewBag.CurrentSort = sortOrder;
            ViewBag.DateSortParm = (String.IsNullOrEmpty(sortOrder) || sortOrder == "date_desc") ? "date" : "date_desc";
            ViewBag.NameSortParm = sortOrder == "name" ? "name_desc" : "name";
            switch (sortOrder)
            {
                case "name":
                    products = products.OrderBy(p => p.Name);
                    break;
                case "name_desc":
                    products = products.OrderByDescending(p => p.Name);
                    break;
                case "date":
                    products = products.OrderBy(p => p.CreateDate);
                    break;
                case "date_desc":
                    products = products.OrderByDescending(p => p.CreateDate);
                    break;
                default:
                    products = products.OrderBy(p => p.Sequence);
                    break;
            }

            //page list
            int pageSize = int.Parse(System.Configuration.ConfigurationManager.AppSettings["PageSize"]);
            int pageNumber = (page ?? 1);
            return View(products.ToPagedList(pageNumber, pageSize));
        }

        // GET: /Product/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: /Product/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Product/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "Id,Name,Category,Description,Detail,ImageName,CreateDate,Sequence")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: /Product/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: /Product/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "Id,Name,Category,Description,Detail,ImageName,CreateDate,Sequence")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: /Product/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: /Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ZiJingHu/Views/Shared/_Action.cshtml
@Html.ActionLink("查看详情 >>", "Details", new { id = Model.Id })
@if (this.Session["IsLogin"] != null && (bool)this.Session["IsLogin"])
{
    <span> | </span>@Html.ActionLink(" ", "Edit", new { id = Model.Id }, new { @class = "glyphicon glyphicon-edit", @title = "编辑" })
    <span> | </span>@Html.ActionLink(" ", "Delete", new { id = Model.Id }, new { @class = "glyphicon glyphicon-trash", @title = "删除" })
}

ZiJingHu/Views/Shared/_Back.cshtml
<div>
    @Html.ActionLink("<< 返回", "Index")
</div>

ZiJingHu/Views/Shared/_CreateNew.cshtml
@if (this.Session["IsLogin"] != null && (bool)this.Session["IsLogin"])
{
    <p>
        @Html.ActionLink("新建", "Create", null, new { @class = "glyphicon glyphicon-new-window", @title = "新建" })
    </p>
}

ZiJingHu/Views/Shared/_EditOrBack.cshtml
<p>    
    @Html.ActionLink("<< 返回", "Index")
    @if (this.Session["IsLogin"] != null && (bool)this.Session["IsLogin"])
    {
        <span> | </span>@Html.ActionLink(" ", "Edit", new { id = Model.Id }, new { @class = "glyphicon glyphicon-edit", @title="编辑" }) 
    }
</p>

ZiJingHu/Views/Shared/_ImageSlides.cshtml
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-pause="false">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
        <li data-target="#myCarousel" data-slide-to="4"></li>
        <li data-target="#myCarousel" data-slide-to="5"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/background/bridge.jpg" alt="First slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Example headline.</h1>
                    <p>Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="~/images/background/energy.jpg" alt="Second slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Another example headline.</h1>
                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="~/images/background/office_automation.jpg" alt="Third slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1>One more for good measure.</h1>
                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="~/Images/Background/Photo_Enforcement.jpg" alt="Fourth slide" />
            <div class="container">
                <div class="carousel-caption">
                    <h1>One more for good measure.</h1>
                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="~/Images/Background/Travel.jpg" alt="Fifth slide" />
            <div class="container">
                <div class="carousel-caption">
                    <h1>One more for good measure.</h1>
                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="~/Images/Background/Website.jpg" alt="Sixth slide" />
            <div class="container">
                <div class="carousel-caption">
                    <h1>One more for good measure.</h1>
                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
                </div>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

ZiJingHu/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <title>紫荆湖科技 - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a href="/"><img src="~/images/logo1.png" class="logo" /></a>

                @*@Html.ActionLink("紫荆湖科技", "Index", "Home", null, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首页", "Index", "Home")</li>
                    <li>@Html.ActionLink("关于我们", "About", "Home")</li>
                    <li>@Html.ActionLink("解决方案及产品", "Index", "Product")</li>
                    @*<li class="dropdown">
                            <a href="#" data-toggle="dropdown" class="dropdown-toggle">解决方案及产品<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                            </ul>
                        </li>*@
                    <li>@Html.ActionLink("服务支持", "Index", "Business")</li>
                    <li>@Html.ActionLink("项目案例", "Index", "Client")</li>
                    <li>@Html.ActionLink("联系我们", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    @if (@ViewBag.Title == "首页")
    {
        @Html.Partial("_ImageSlides")
    }

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <span class="glyphicon glyphicon-phone-alt glyphicon-print"></span>&nbsp;国内(+086)139-85672920&nbsp;&nbsp;国际(+001)850-5913459&nbsp;
            <span class="glyphicon glyphicon-envelope"></span>&nbsp;info@zijinghu.com<br />
            <div class="glyphicon">&copy;</div>@DateTime.Now.Year-紫荆湖科技有限公司版权所有&nbsp;@*粤ICP备19056482号*@
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")*@
    <script type="text/javascript" src="~/Scripts/jquery-1.10.2.min.js"></script>
    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("scripts", required: false)

    @if (this.Session["IsLogin"] != null && (bool)this.Session["IsLogin"])
    {
        //cleditor
        <link rel="stylesheet" type="text/css" href="~/CLEditor/jquery.cleditor.css" />
        <script type="text/javascript" src="~/CLEditor/jquery.cleditor.min.js"></script>
        //jquery UI
        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
        <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
    }

    <script type="text/javascript">
        $(document).ready(function () {
            /*
            //display categories
            $.getJSON('/Helper/GetCategories', null, function (data) {
                $.each(data, function (index, item) {
                    $(".dropdown-menu").append('<li><a href=/Product/Index#' + item.Value + '>' + item.DisplayName + '</a></li>');
                });
            });*/

            if ($("#includedContent") != null) $("#includedContent").load("background.html");

            //WYSIWYG: what you see is what you get
            $(".cleditor-textarea").cleditor();

            //date picker
            $('.datepicker').datepicker();
        });
    </script>

</body>
</html>